### ISSUE TITLE
Some of retail gpks cannot be opened

### ISSUE THREAD

**Issue by Zerraa** [GoneUp/GPK_RePack#15]
Hi! 
When editing some gpks, there is an error when opening them:

```
17:46:17 GUI # Startup
17:46:21 [ReadSubGpkPackage:S1UI_Nameplate.gpk_0] # Parse failure!
17:46:21 [ReadSubGpkPackage:S1UI_Nameplate.gpk_0] # System.Exception: NameIndex 14899241549880 not found!
   at GPK_RePack.Model.GpkPackage.GetString(Int64 index)
   at GPK_RePack.IO.Reader.ReadImports(BinaryReader reader, GpkPackage package)
   at GPK_RePack.IO.Reader.ReadSubGpkPackage(GpkPackage package, Byte[] data, Boolean skipExportData, Status stat)
17:46:21 [ReadSubGpkPackage:S1UI_Nameplate.gpk_0] # Reading of file C:\Games\S1UI_Nameplate.gpk complete, took 65ms!
```

any hope for a fix?

**Comment by GoneUp** [comment]
Not really, sorry. I stopped playing tera a long time ago and won't download it again. 
You can try [RealEditor](https://github.com/VenoMKO/RealEditor), it still looks active.

**Comment by Zerraa** [comment]
Unlucky, thanks for the reply though
